.PHONY: run-user-proj-tests
run-user-proj-tests:
	@echo "Ejecutando hello_world_uart con caravel_cocotb..."
	@../../../venv-cocotb/bin/python3 -m caravel_cocotb -t hello_world_uart -tag hello_world_yaml

